Description: Deploy an EC2 instance in an AWS Default VPC

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-035be7bafff33b6b6
    us-east-2:
      AMI: ami-04328208f4f0cf1fe

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Role
          Value: Training
        - Key: Join Example
          Value: !Join [ -, [ one, string, from, many, parts ] ]
        - Key: Account ID Reference Example
          Value: !Ref AWS::AccountId
        - Key: AMI
          Value: !FindInMap
            - RegionMap
            - !Ref AWS::Region
            - AMI