Description: Deploy an EC2 instance in an AWS Default VPC

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-035be7bafff33b6b6
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Role
          Value: Training