Description: Deploy an EC2 instance in an AWS Default VPC

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-035be7bafff33b6b6
    us-east-2:
      AMI: ami-04328208f4f0cf1fe

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t2.micro
      - t2.small

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: 
                !Sub |
                  <head>
                    <title>This page created with cfn-init</title>
                  </head>
                  <body>
                  <h1>Welcome to my IaC site!</h1>
                  <p>This server/site was deployed with CloudFormation.</p>
                  <p>#doingitright</p>
                  </body>
                  </html>
          commands:
            update_packages:
              command: yum update --assumeyes
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
    Properties:
      SecurityGroups:
        - !Ref SecurityGroup
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: !Ref InstanceType
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Role
          Value: Training
        - Key: Join Example
          Value: !Join [ -, [ one, string, from, many, parts ] ]
        - Key: Account ID Reference Example
          Value: !Ref AWS::AccountId
        - Key: AMI
          Value: !FindInMap
            - RegionMap
            - !Ref AWS::Region
            - AMI

  SecurityGroup:
    Type:  AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Firewall exceptions
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: HTTP
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      Tags:
        - Key: Name
          Value: My Security Group

Outputs:
  PublicDNS:
    Description: EC2 instance public DNS name
    Value: !GetAtt EC2Instance.PublicDnsName